# Generated by Django 5.1.5 on 2025-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0007_remove_answer_voter_remove_comment_modify_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
