# Generated by Django 5.1.5 on 2025-06-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0008_alter_answer_modify_date_alter_question_modify_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
