# Generated by Django 5.2.3 on 2025-06-15 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0009_alter_answer_create_date_alter_question_create_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="voter",
            field=models.ManyToManyField(
                related_name="voter_answer", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="voter",
            field=models.ManyToManyField(
                related_name="voter_question", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
